v.1
allnes/pp_2021_spring_engineers pull request #35
Opened 2021-03-26 17:10 UTC by KamskovEM

2021-04-01 20:29 UTC, allnes requested changes

2021-04-01 20:29 UTC, allnes commented on modules/task_1/kamskov_e_shell_batcher_sort/CMakeLists.txt
> +if ( USE_SEQ )
не правильный cmake, я произвел изменения в этой версии репозитория и все примеры нудно брать с директории modules/test_task

2021-04-02 07:50 UTC, KamskovEM commented on modules/task_1/kamskov_e_shell_batcher_sort/CMakeLists.txt
> +if ( USE_SEQ )
Поменял. А я сегодня очно сдавал, незаметив вашего комментария, будет засчитана сдача?

2021-04-02 12:18 UTC, allnes requested changes

2021-04-02 12:18 UTC, allnes commented on modules/task_1/kamskov_e_shell_batcher_sort/CMakeLists.txt
> +if ( USE_STD )
неправильный cmakelists, он для задачи 4

2021-04-02 12:19 UTC, allnes commented on modules/task_1/kamskov_e_shell_batcher_sort/CMakeLists.txt
> +if ( USE_SEQ )
я вас не отметил, придется передсать с правильным cmake, потому что вы в принципе были не допущены

2021-04-08 22:23 UTC, allnes approved these changes

2021-04-08 22:23 UTC, merged